Feature/initializer
kalj/StenSeal pull request #8
Opened 2017-01-25 12:49 UTC by ylvarydin

Vad håller vi på med? Är det här ens nästan rätt?!

2017-01-25 13:55 UTC, kalj commented
Bra början. :)

Först så har vi väl två olika ändringar i ett här, dels initialiseringen, och dels stencilerna. Jag tycker att vi kan skippa stencilerna, eftersom vi ändå har ett nytt sätt att specificera dem på gång i #7. Enklast är nog att bara ta bort den committen (2466b06), och sedan force-pusha. @Werpers kanske hjälpa till här?

Sedan finns det ett par problem i koden:
* Det verkar smugit sig in en massa whitespace i `wave-equation.cc`, typ en tab i början på varje rad. Fixa det så att det är två spaces som skillnad i nivå mellan varje block (detta har vi inte diskuterat, men jag gör ett försök att bestämma det härmed. :) ).
* I 2D-fallet tror jag att det blivit knas med indexen. Jag antar att vi vill ha att att x-variabeln går "snabbast", dvs x borde räknas ut från j. Lägger in en inline-kommentar om förslag på lösning.

2017-01-25 13:58 UTC, kalj requested changes
Förslag på hur loop-ordningen kan bytas så att x går "snabbast"

2017-01-25 13:58 UTC, kalj commented on examples/wave-equation.cc
> +         for(int j = 0; j < g.n_nodes[1]; ++j) {
Byt bounds på looparna.

2017-01-25 13:58 UTC, kalj commented on examples/wave-equation.cc
> +            u[g.n_nodes[1]*i+j] = f.value(p);
Byt till `n_nodes[0]`

2017-01-25 13:58 UTC, kalj commented on examples/wave-equation.cc
> +            y = j*g.h[1] + g.lower_left(1);
Byt plats på `i` och `j`.

2017-01-26 14:06 UTC, ylvarydin commented
Tror att jag har fixat allt nu :)

2017-01-26 15:13 UTC, ylvarydin commented
Har ändrat indexen

2017-01-26 15:23 UTC, kalj approved these changes

2017-01-26 15:24 UTC, kalj commented
Snyggt! Jag är nöjd nu. Om inte @Werpers har nån synpunkt, så mergear jag innan jag går hem.

2017-01-26 16:05 UTC, merged